# Generated by Django 5.1.5 on 2025-02-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='budget_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
