# Generated by Django 5.1.5 on 2025-05-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0007_khodro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khodro',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
