# Generated by Django 5.1.5 on 2025-05-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0008_alter_khodro_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mission_type',
            field=models.CharField(choices=[('normal', 'ماموریت عادی'), ('half', 'ماموریت اصالت'), ('holiday', 'ماموریت تعطیل')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='mission',
            name='mission_units',
            field=models.FloatField(default=1, editable=False),
        ),
    ]
