# Generated by Django 5.1.5 on 2025-05-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0010_remove_mission_mission_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mission_type',
            field=models.CharField(choices=[('normal', 'ماموریت عادی'), ('half', 'ماموریت اصالت'), ('holiday', 'ماموریت تعطیل')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='mission',
            name='mission_units',
            field=models.FloatField(default=1, editable=False),
        ),
    ]
